### ISSUE TITLE
Sending non-protected broadcast

### ISSUE THREAD

**Issue by VladBarsCitadele** [ondato/ondato-sdk-android#10]
In versions 2.5.2 and 2.5.3 we encounter the following issues :

```
10:10:40.167  E  Sending non-protected broadcast com.samsung.intent.action.MEDIA_PROJECTION_PERMISSION from system 2681:com.android.systemui/u0a63 pkg com.android.systemui
                 java.lang.Throwable
                 	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:16981)
                 	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:17921)
                 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:17069)
                 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:17046)
                 	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:18148)
                 	at android.app.IActivityManager$Stub.onTransact$broadcastIntentWithFeature$(IActivityManager.java:11607)
                 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2945)
                 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
                 	at android.os.Binder.execTransactInternal(Binder.java:1380)
                 	at android.os.Binder.execTransact(Binder.java:1311)

10:10:41.653  E  FATAL EXCEPTION: DefaultDispatcher-worker-6
                 Process: lv.citadele.mobile.cimo.testapp, PID: 26803
                 java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.
                 	at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:214)
                 	at v.e.a(Unknown Source:27)
                 	at v.h.c(Unknown Source:21)
                 	at v.j.<init>(Unknown Source:27)
                 	at v.a.a(Unknown Source:23)
                 	at com.ondato.sdk.recorder.RecorderService$c.invokeSuspend(Unknown Source:61)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9a52a3c, Dispatchers.IO]
```
on 2.5.2 its the same if we add FOREGROUND_SERVICE_MEDIA_PROJECTION on our side.

**Comment by VladBarsCitadele** [comment]
The current app uses target sdk 34 to accompany the need of FOREGROUND_SERVICE_MEDIA_PROJECTION.

**Comment by edgaras-simanavicius** [comment]
@VladBarsCitadele Hello, managed to find a device that this reproduces on, a fix is on the way.

**Comment by VladBarsCitadele** [comment]
@edgaras-simanavicius Great news ! Any word when we could expect the fix ?

**Comment by edgaras-simanavicius** [comment]
https://github.com/ondato/ondato-sdk-android/releases/tag/2.5.4
