### ISSUE TITLE
Bug Report: startIdentification Method - NoSuchMethodError

### ISSUE THREAD

**Issue by kosciukw** [ondato/ondato-sdk-android#18]
I am encountering a NoSuchMethodError when calling the  Ondato.INSTANCE.startIdentification method from the Ondato SDK v2.5.14. The error is related to a mismatch between Kotlin and Koin versions. Specifically, I’m using Kotlin 1.9.22 and Koin 3.5.3, while the Ondato SDK seems to use Kotlin 1.8.0 and Koin 3.2.4.

> E  java.lang.NoSuchMethodError: No static method bind(Lkotlin/Pair;Lkotlin/reflect/KClass;)Lkotlin/Pair; in class Lorg/koin/dsl/DefinitionBindingKt; or its super classes (declaration of 'org.koin.dsl.DefinitionBindingKt' appears in /data/app/~~GIYTFwlWbrLOa5IXk5eRuw==/com.verestro.svl.beta-Z2dJ6IRROnu_ZZCCLtGM8A==/base.apk!classes30.dex)
    at com.ondato.sdk.c.v.invoke(SourceFile:138)
    at org.koin.dsl.ModuleDSLKt.module(ModuleDSL.kt:45)
    at org.koin.dsl.ModuleDSLKt.module$default(ModuleDSL.kt:43)
    at com.ondato.sdk.t.b.invoke(SourceFile:93)
    at com.ondato.sdk.t.c.startKoin(SourceFile:7)
    at com.ondato.sdk.Ondato.startIdentification(SourceFile:6)
    at com.verestro.ondato.sdk.controller.impl.OndatoSdkControllerImpl$startIdentification$2.invoke(OndatoSdkControllerImpl.kt:25)
    at com.verestro.ondato.sdk.controller.impl.OndatoSdkControllerImpl$startIdentification$2.invoke(OndatoSdkControllerImpl.kt:24)
    at com.verestro.core.callback.CallbackWrapperKt.suspendCallback(CallbackWrapper.kt:13)
    at com.verestro.core.callback.CallbackWrapperKt.suspendCallback$default(CallbackWrapper.kt:8)
    at com.verestro.ondato.sdk.controller.impl.OndatoSdkControllerImpl.startIdentification(OndatoSdkControllerImpl.kt:24)
    at com.verestro.ondato.usecase.VerifyIdentityUseCase.action(VerifyIdentityUseCase.kt:11)
    at com.verestro.ondato.usecase.VerifyIdentityUseCase.action(VerifyIdentityUseCase.kt:6)
    at pl.upaid.mvvm.core.domain.UseCase$executeAction$2.invokeSuspend(UseCase.kt:14)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

    
I've tested different ondato SDK versions and the issue persists. I can't however decrease my koin/kotlin configuration to match ondato.

**Comment by nedas-matulevicius** [comment]
Hi @kosciukw, thanks for reporting your issue! We're currently working on this and will update you as soon as the fixes  related to the issue you're facing will be done. 

Please note that during the current holiday season the updates could come later than usual. Thank you for your patience and understanding!
