### ISSUE TITLE
Pressing back button while SDK loads causes several exceptions

### ISSUE THREAD

**Issue by andriusalekna** [ondato/ondato-sdk-android#6]
1) This is common issue for 1.8.xx versions and I managed to reproduce it several times with 2.5.2.
Just by pressing back from Ondato loading screen or first landing screen.
```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{de.kurts.sharing.staging/com.ondato.sdk.ui.launcher.LauncherActivity}: java.lang.IllegalStateException: DI is not initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3812)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.IllegalStateException: DI is not initialized
	at u.c.get(SourceFile:1)
	at d0.a.getKoin(SourceFile:1)
	at org.koin.android.ext.android.AndroidKoinScopeExtKt.getKoinScope(AndroidKoinScopeExt.kt:17)
	at com.ondato.sdk.ui.launcher.LauncherActivity.<init>(SourceFile:19)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:44)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1362)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3797)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
```
	

2) Currently in production we are using 1.8.xx version and I didnt see this error in crashlytics, but its very easy reproducable by pressing back while SDK is loading.
	
```
	java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 10
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.j
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at p0.h.b(SourceFile:2)
	at p0.f.k(SourceFile:45)
	at com.ondato.sdk.ui.main.MainActivity.onBackPressed(SourceFile:1)
	at android.app.Activity.onKeyUp(Activity.java:4020)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2931)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4377)
```
https://github.com/ondato/ondato-sdk-android/assets/154411783/99cbbc81-03bc-4ae9-9b37-973d88183f75

**Comment by Svaike** [comment]
Hi, we are no longer maintaining v1.x.x, but we'll look into the issue with 2.5.2. Thank you for reporting it.
