### ISSUE TITLE
Crash during debug

### ISSUE THREAD

**Issue by Ein6tein** [ondato/ondato-sdk-android#9]
Hello,

Using android-sdk v2.5.3, launched via debug and got this exception:
```
FATAL EXCEPTION: main
Process: our.app.package, PID: 7493
java.lang.RuntimeException: Unable to start activity ComponentInfo{our.app.package/com.ondato.sdk.ui.launcher.LauncherActivity}: java.lang.IllegalStateException: DI is not initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.IllegalStateException: DI is not initialized
	at s.b.get(Unknown Source:21)
	at s.a$a.a(Unknown Source:2)
	at b0.a.getKoin(Unknown Source:0)
	at org.koin.android.ext.android.AndroidKoinScopeExtKt.getKoinScope(AndroidKoinScopeExt.kt:17)
	at com.ondato.sdk.ui.launcher.LauncherActivity$k.a(Unknown Source:8)
	at com.ondato.sdk.ui.launcher.LauncherActivity$k.invoke(Unknown Source:0)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:48)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
	at com.ondato.sdk.ui.launcher.LauncherActivity.g(Unknown Source:2)
	at com.ondato.sdk.ui.launcher.LauncherActivity.onCreate(Unknown Source:41)
	at android.app.Activity.performCreate(Activity.java:8975)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:230) 
	at android.os.Looper.loop(Looper.java:319) 
	at android.app.ActivityThread.main(ActivityThread.java:8918) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
```

**Comment by edgaras-simanavicius** [comment]
https://github.com/ondato/ondato-sdk-android/releases/tag/2.5.4
